version: '3'
services:
  application:
    build: ./Docker/code
    volumes:
      - .:/var/www/laravel
    tty: true
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bot
      TEST_DB_NAME: bot_test
      MYSQL_USER: bot_root
      MYSQL_PASSWORD: bot_root
    depends_on:
      - application
    ports:
      - 6606:3306
    mem_limit: 7000m  
  php:
    build: ./Docker/php-fpm
    environment:
      MAIL_ENCRYPTION: 0
      MAIL_PRETEND: 0
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
    volumes_from:
      - application
    depends_on:
      - application
      - db
    links:
      - db
    user: "1000:1000"
  nginx:
    build: ./Docker/nginx
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - db
      - php
    ports:
      - 4001:80
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '18080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
